package Test;

import Modelos.*;
import Controladores.*;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;

/**
 *
 * @author Grupo2
 */
public class Test {

    public static void main(String[] args) {
        Patologia cardiopatia = new Patologia("Cardiopatia");
        Patologia migrania = new Patologia("Migraña");
        Patologia sobrepeso = new Patologia("Sobrepeso");
        LocalDate fecha1 = LocalDate.parse("1988-11-09");
        LocalDate fecha2 = LocalDate.parse("1956-11-03");
        LocalDate fecha3 = LocalDate.parse("1994-03-20");
        Persona eze = new Persona(sobrepeso, 34229421, "Jorge Ezequiel", "Diaz", 98.0, 1.75, "diazezquiel777@gmail.com", false, "1132185230", fecha1, "San Luis", "Ciudad de San Luis");
        Persona dora = new Persona(null, 12600842, "Dora Nelida", "Orsomarso", 65.0, 1.65, "doranel50@hotmail.com", true, "1163213910", fecha2, "Buenos Aires", "San Martin");
        Persona fede = new Persona(migrania, 37716731, "Federico Ivan", "Cruceño", 80.0, 1.72, "fedeicru@gmail.com", false, "2657312733", fecha3, "San Luis", "Villa Mercedes");
        Laboratorio pfizer = new Laboratorio("Charles Pfizer 1849", "Pfizer", "Estados Unidos");
        Laboratorio gamaleya = new Laboratorio("Nicholay Gamaleya 1948", "Sputnik V", "Rusia");
        Laboratorio astrazeneca = new Laboratorio("Astra Zeneca 2020", "AstraZeneca", "Reino Unido");
        CentroDeVacunacion ce1 = new CentroDeVacunacion("Hospital Cerro de la Cruz", "Ciudad de San Luis", "San Luis");
        CentroDeVacunacion ce2 = new CentroDeVacunacion("Hospital de Villa Mercedes", "Villa Mercedes", "San Luis");
        CentroDeVacunacion ce3 = new CentroDeVacunacion("Hospital Zubizarreta", "CABA", "Devoto");
        LocalDate fecha4 = LocalDate.parse("2021-09-14");
        LocalDate fecha5 = LocalDate.parse("2021-10-09");
        LocalDate fecha6 = LocalDate.parse("2021-11-09");
        LocalTime hora1 = LocalTime.parse("16:30:00");
        LocalTime hora2 = LocalTime.parse("10:30:00");
        LocalTime hora3 = LocalTime.parse("15:30:00");
        PatologiaData pad = new PatologiaData();
        PersonaData ped = new PersonaData();
        LaboratorioData ld = new LaboratorioData();
        System.out.println(" PRUEBA DE LOS METODOS DE LA CLASE PATOLOGIASDATA:");
        System.out.println("             -                    -                    -                    -                    -                    -                    -");
        System.out.println("Guardado de las patologias en la BD: ");
        pad.guardarPatologia(migrania);
        pad.guardarPatologia(sobrepeso);
        pad.guardarPatologia(sobrepeso);
        pad.guardarPatologia(cardiopatia);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de patologias: ");
        System.out.println(pad.obtenerPatologias());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Actualizacion del nombre de la patologia: ");
        migrania.setNombrePatologia("Dolor de cabeza");
        pad.actualizarNombreDeLaPatologia(migrania);
        pad.actualizarNombreDeLaPatologia(sobrepeso);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Patologia: " + pad.buscarPatologia(migrania.getIdPatologia()));
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Borrado de patologia: ");
        pad.borrarPatologia(migrania.getIdPatologia());
        pad.borrarPatologia(migrania.getIdPatologia());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de patologias: ");
        System.out.println(pad.obtenerPatologias());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Reguardado de la patologia borrada: ");
        migrania.setNombrePatologia("Migrania");
        pad.guardarPatologia(migrania);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de patologias: ");
        System.out.println(pad.obtenerPatologias());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println(" PRUEBA DE LOS METODOS DE LA CLASE PERSONADATA:");
        System.out.println("             -                    -                    -                    -                    -                    -                    -");
        System.out.println("Guardado de las personas en la BD: ");
        ped.guardarPersona(dora);
        ped.guardarPersona(eze);
        ped.guardarPersona(eze);
        ped.guardarPersona(fede);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de personas: ");
        System.out.println(ped.obtenerPersonas());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Actualizacion del nombre, del trabajo y del departamento de persona: ");
        eze.setNombre("Ezequiel");
        dora.setTrabajo(false);
        fede.setDepartamento("Ciudad de San Luis");
        ped.actualizarPersona(eze);
        ped.actualizarPersona(fede);
        ped.actualizarPersona(fede);
        ped.actualizarPersona(dora);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Persona: " + ped.buscarPersona(dora.getIdPersona()));
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Borrado de persona: ");
        ped.borrarPersona(dora.getIdPersona());
        ped.borrarPersona(dora.getIdPersona());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de personas: ");
        System.out.println(ped.obtenerPersonas());
        dora.setTrabajo(true);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Reguardado de la persona borrada: ");
        ped.guardarPersona(dora);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de personas: ");
        System.out.println(ped.obtenerPersonas());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println(" PRUEBA DE LOS METODOS DE LA CLASE LABORATORIODATA:");
        System.out.println("             -                    -                    -                    -                    -                    -                    -");
        System.out.println("Guardado de los laboratorios en la BD: ");
        ld.guardarLaboratorio(pfizer);
        ld.guardarLaboratorio(gamaleya);
        ld.guardarLaboratorio(gamaleya);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de laboratorios: ");
        System.out.println(ld.obtenerLaboratorios());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Actualizacion del nombre y el pais de origen de laboratorio");
        pfizer.setNombreComercial("pize");
        gamaleya.setPaisDeOrigen("Russia");
        ld.actualizarLaboratorio(pfizer);
        ld.actualizarLaboratorio(gamaleya);
        ld.actualizarLaboratorio(gamaleya);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Laboratorio: " + ld.buscarLaboratorio(gamaleya.getIdLaboratorio()));
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Borrado de laboratorio: ");
        ld.borrarLaboratorio(gamaleya.getIdLaboratorio());
        ld.borrarLaboratorio(gamaleya.getIdLaboratorio());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de laboratorios: ");
        System.out.println(ld.obtenerLaboratorios());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        pfizer.setNombreComercial("Pfizer");
        gamaleya.setPaisDeOrigen("Rusia");
        ld.actualizarLaboratorio(pfizer);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Reguardado del laboratorio borrado: ");
        ld.guardarLaboratorio(gamaleya);
        ld.guardarLaboratorio(astrazeneca);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de laboratorios: ");
        System.out.println(ld.obtenerLaboratorios());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        Dosis dosis1 = new Dosis(true, 1, pfizer);
        Dosis dosis2 = new Dosis(true, 2, gamaleya);
        Dosis dosis3 = new Dosis(true, 3, gamaleya);
        Dosis dosis4 = new Dosis(true, 4, astrazeneca);
        Dosis dosis5 = new Dosis(true, 4, astrazeneca);
        DosisData dd = new DosisData();
        System.out.println(" PRUEBA DE LOS METODOS DE LA CLASE DOSISDATA:");
        System.out.println("             -                    -                    -                    -                    -                    -                    -");
        System.out.println("Guardado de las dosis en la BD: ");
        dd.guardarDosis(dosis1);
        dd.guardarDosis(dosis2);
        dd.guardarDosis(dosis2);
        dd.guardarDosis(dosis3);
        dd.guardarDosis(dosis4);
        dd.guardarDosis(dosis5);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de dosis: ");
        System.out.println(dd.obtenerDosis());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Actualizacion del estado y el nombre del laboratorio de las vacunas: ");
        dosis1.setEstado(false);
        dosis2.setLaboratorio(pfizer);
        dd.actualizarDosis(dosis1);
        dd.actualizarDosis(dosis2);
        dd.actualizarDosis(dosis2);
        dd.actualizarDosis(dosis3);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("dosis: " + dd.buscarDosis(dosis2.getIdDosis()));
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Borrado de dosis: ");
        dd.borrarDosis(dosis2.getIdDosis());
        dd.borrarDosis(dosis2.getIdDosis());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de dosis: ");
        System.out.println(dd.obtenerDosis());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Reguardado de la dosis borrada: ");
        dosis1.setEstado(true);
        dosis2.setLaboratorio(gamaleya);
        dd.actualizarDosis(dosis1);
        dd.guardarDosis(dosis2);
        dd.actualizarDosis(dosis2);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de dosis: ");
        System.out.println(dd.obtenerDosis());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        CentroDeVacunacionData ced = new CentroDeVacunacionData();
        System.out.println(" PRUEBA DE LOS METODOS DE LA CLASE CENTRODEVACUNACIONDATA:");
        System.out.println("             -                    -                    -                    -                    -                    -                    -");
        System.out.println("Guardado de los centros de vacunacion en la BD: ");
        ced.guardarCentroDeVacunacion(ce1);
        ced.guardarCentroDeVacunacion(ce1);
        ced.guardarCentroDeVacunacion(ce2);
        ced.guardarCentroDeVacunacion(ce3);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de centros de vacunacion: ");
        System.out.println(ced.obtenerCentrosDeVacunaciones());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Actualizacion del nombre, de la ciudad y del departamentos de los centros de vacunacion: ");
        ce1.setNombreCentroDeVacunacion("Hospital Policlinico");
        ce2.setDepartamento("Ciudad de Villa Mercedes");
        ce3.setCiudad("Ciudad Autonoma de Buenos Aires");
        ced.actualizarCentroDeVacunacion(ce1);
        ced.actualizarCentroDeVacunacion(ce1);
        ced.actualizarCentroDeVacunacion(ce2);
        ced.actualizarCentroDeVacunacion(ce3);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Centro de Vacunacion: " + ced.buscarCentroDeVacunacion(ce2.getIdCentroDeVacunacion()));
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Borrado del centro de vacunacion: ");
        ced.borrarCentroDeVacunacion(ce3.getIdCentroDeVacunacion());
        ced.borrarCentroDeVacunacion(ce3.getIdCentroDeVacunacion());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de centros de vacunacion: ");
        System.out.println(ced.obtenerCentrosDeVacunaciones());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Reguardado de los centros de vacunacion: ");
        ced.guardarCentroDeVacunacion(ce3);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de centros de vacunacion: ");
        System.out.println(ced.obtenerCentrosDeVacunaciones());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        CitaDeVacunacion ci1 = new CitaDeVacunacion(fecha4, hora1, true, ce3, dora, dosis2);
        CitaDeVacunacion ci2 = new CitaDeVacunacion(fecha5, hora2, true, ce2, fede, dosis1);
        CitaDeVacunacion ci3 = new CitaDeVacunacion(fecha6, hora3, true, ce1, eze, dosis3);
        CitaDeVacunacionData cid = new CitaDeVacunacionData();
        System.out.println(" PRUEBA DE LOS METODOS DE LA CLASE CITADEVACUNACIONDATA:");
        System.out.println("             -                    -                    -                    -                    -                    -                    -");
        System.out.println("Guardado de las citas de vacunacion en la BD: ");
        cid.guardarCitaDeVacunacion(ci1);
        cid.guardarCitaDeVacunacion(ci2);
        cid.guardarCitaDeVacunacion(ci3);
        cid.guardarCitaDeVacunacion(ci3);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de citas de vacunacion: ");
        System.out.println(cid.obtenerCitasDeVacunaciones());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Actualizacion del estado de la cita de vacunacion: ");
        ci1.setEstadoDeCita(false);
        ci2.setPersona(eze);
        ci3.setDosis(dosis5);
        ci3.setCentroDeVacunacion(ce2);
        cid.actualizarCitaDeVacunacion(ci1);
        cid.actualizarCitaDeVacunacion(ci2);
        cid.actualizarCitaDeVacunacion(ci3);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Cita de vacunacion: " + cid.buscarCentroDeVacunacion(ci1.getIdCitaDeVacunacion()));
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Borrado de la cita de vacunacion: ");
        cid.borrarCentroDeVacunacion(ci2.getIdCitaDeVacunacion());
        cid.borrarCentroDeVacunacion(ci2.getIdCitaDeVacunacion());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de citas de vacunacion: ");
        System.out.println(cid.obtenerCitasDeVacunaciones());
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Reguardado de la cita de vacunacion: ");
        ci1.setEstadoDeCita(true);
        ci2.setPersona(fede);
        ci2.setDosis(dosis3);
        ci3.setCentroDeVacunacion(ce1);
        cid.actualizarCitaDeVacunacion(ci1);
        cid.actualizarCitaDeVacunacion(ci2);
        cid.actualizarCitaDeVacunacion(ci3);
        cid.guardarCitaDeVacunacion(ci2);
        System.out.println("------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Lista de citas de vacunacion: ");
        System.out.println(cid.obtenerCitasDeVacunaciones());
    }
}