package Vistas;

/**
 *
 * @author Grupo2
 */
public class viewMenu extends javax.swing.JFrame {

    /**
     * Creates new form viewMenu
     */
    public viewMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMagregarPersona = new javax.swing.JMenuItem();
        JMeditarPersona = new javax.swing.JMenuItem();
        JMlistarPersona = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMagregarLaboratorio = new javax.swing.JMenuItem();
        JMmodificarLaboratorio = new javax.swing.JMenuItem();
        JMlistarLaboratorio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JMsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1269, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jMenu1.setText("Persona");

        JMagregarPersona.setText("Agregar Persona");
        JMagregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMagregarPersonaActionPerformed(evt);
            }
        });
        jMenu1.add(JMagregarPersona);

        JMeditarPersona.setText("Editar o quitar persona");
        jMenu1.add(JMeditarPersona);

        JMlistarPersona.setText("Listar persona");
        jMenu1.add(JMlistarPersona);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laboratorio");

        JMagregarLaboratorio.setText("Agregar Laboratorio");
        jMenu2.add(JMagregarLaboratorio);

        JMmodificarLaboratorio.setText("Modifcar/Eliminar Laboratorio");
        jMenu2.add(JMmodificarLaboratorio);

        JMlistarLaboratorio.setText("Listar Laboratorio");
        jMenu2.add(JMlistarLaboratorio);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");

        JMsalir.setText("Salir");
        JMsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMsalirActionPerformed(evt);
            }
        });
        jMenu3.add(JMsalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMsalirActionPerformed
        // TODO add your handling code here:
        dispose ();
    }//GEN-LAST:event_JMsalirActionPerformed

    private void JMagregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMagregarPersonaActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();
        escritorio.repaint();
        viewAgregarPersona vap = new viewAgregarPersona();
        vap.setVisible(true);
        escritorio.add(vap);
        escritorio.moveToFront(vap);
    }//GEN-LAST:event_JMagregarPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMagregarLaboratorio;
    private javax.swing.JMenuItem JMagregarPersona;
    private javax.swing.JMenuItem JMeditarPersona;
    private javax.swing.JMenuItem JMlistarLaboratorio;
    private javax.swing.JMenuItem JMlistarPersona;
    private javax.swing.JMenuItem JMmodificarLaboratorio;
    private javax.swing.JMenuItem JMsalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
