/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.CentroDeVacunacionData;
import Modelos.CentroDeVacunacion;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class viewAgBusElCentro extends javax.swing.JInternalFrame {

    private CentroDeVacunacionData centroVacunacion;
    
    /**
     * Creates new form viewAgBusElCentro
     */
    public viewAgBusElCentro(CentroDeVacunacionData centroVacunacion) {
        initComponents();
        this.centroVacunacion = centroVacunacion;
    }
    
    public CentroDeVacunacion guardarCentro() {
    CentroDeVacunacion centro = new CentroDeVacunacion(jtfNombreCentro.getText(), jtfCiudad.getText(), jtfDepartamento.getText());
            return centro;
    }
    
    public void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    
    public CentroDeVacunacion buscarCentro() {
        ArrayList<CentroDeVacunacion> lista = centroVacunacion.obtenerCentrosDeVacunaciones();
        CentroDeVacunacion Centro = null;
        if (jtfNombreCentro.getText() == "" ) {
            mensaje("Debe completar con nombre para eliminar");
            return Centro;
        }
        for (int i = 0; i < lista.size(); i++) {
            if (jtfNombreCentro.getText() == lista.get(i).getNombreCentroDeVacunacion()) {
                Centro = lista.get(i);
                return Centro;
            }
        }
        mensaje("No existe ninguna centro con el Nombre: " + jtfNombreCentro.getText());
        return Centro;
    }
    
    
     public void limpiar() {
        jtfNombreCentro.setText("");
        jtfDepartamento.setText("");
        jtfCiudad.setText("");
     }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNombreCentro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfCiudad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfDepartamento = new javax.swing.JTextField();
        jbAgregarCentro = new javax.swing.JButton();
        jbBuscarCentro = new javax.swing.JButton();
        jbEliminarCentro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestor de centro de vacunacion");

        jLabel2.setText("Nombre Centro de Vacunacion:");

        jtfNombreCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreCentroActionPerformed(evt);
            }
        });

        jLabel3.setText("Ciudad:");

        jtfCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCiudadActionPerformed(evt);
            }
        });

        jLabel4.setText("Departamento:");

        jbAgregarCentro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        jbAgregarCentro.setText("Agregar");
        jbAgregarCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarCentroActionPerformed(evt);
            }
        });

        jbBuscarCentro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lupa miniatura.png"))); // NOI18N
        jbBuscarCentro.setText("Buscar");
        jbBuscarCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarCentroActionPerformed(evt);
            }
        });

        jbEliminarCentro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        jbEliminarCentro.setText("Eliminar");
        jbEliminarCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarCentroActionPerformed(evt);
            }
        });

        jLabel6.setText("Para agregar un centro de vacunacion llene todos los campos y presione 'enter' o haga click en el boton 'más'.");

        jLabel7.setText("Para buscar un centro llene el campo Nombre y haga click en la lupa para poder visualizar todos sus datos.");

        jLabel8.setText("Complete el campo Nombre y precione Eliminar para suprimir un centro de vacunacion.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(262, 262, 262))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfNombreCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel4)))
                                .addGap(45, 45, 45)
                                .addComponent(jtfDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbEliminarCentro)
                                    .addComponent(jbBuscarCentro))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbAgregarCentro)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombreCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarCentro)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscarCentro)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEliminarCentro)
                    .addComponent(jLabel8))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreCentroActionPerformed

    private void jtfCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCiudadActionPerformed

    private void jbEliminarCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarCentroActionPerformed
        // TODO add your handling code here:
        centroVacunacion.borrarCentroDeVacunacion(buscarCentro().getIdCentroDeVacunacion());
        limpiar();
    }//GEN-LAST:event_jbEliminarCentroActionPerformed

    private void jbBuscarCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarCentroActionPerformed
        // TODO add your handling code here:
        centroVacunacion.buscarCentroDeVacunacion(buscarCentro().getIdCentroDeVacunacion());
        limpiar();
    }//GEN-LAST:event_jbBuscarCentroActionPerformed

    private void jbAgregarCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarCentroActionPerformed
        // TODO add your handling code here:
        centroVacunacion.guardarCentroDeVacunacion(guardarCentro());
        limpiar();
    }//GEN-LAST:event_jbAgregarCentroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAgregarCentro;
    private javax.swing.JButton jbBuscarCentro;
    private javax.swing.JButton jbEliminarCentro;
    private javax.swing.JTextField jtfCiudad;
    private javax.swing.JTextField jtfDepartamento;
    private javax.swing.JTextField jtfNombreCentro;
    // End of variables declaration//GEN-END:variables
}
